version: "3"

services:
  server:
    build:
      context: ./rmtp-server
      dockerfile: ./Dockerfile
    ports:
      - "0.0.0.0:3333:3333"

  client:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    ports:
      - "0.0.0.0:3000:3000"
