version: "3"

services:
  rmtp_server:
    build:
      context: ./rmtp-server
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
  krappa-tv:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
